import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

export type AuditStatus = "success" | "failed" | "info";
export type AuditEntry = { id: string; clientId: string; at: string; action: string; status: AuditStatus; detail: string; durationMs?: number; errorCode?: string; requestId?: string };
export type Client = { id: string; slug: string; companyName: string; siigoUsername: string; accessKeyEncrypted: string; partnerId: string; apiKeyHash: string; apiKeyPrefix: string; connectionStatus: "unconfigured" | "connected" | "error"; createdAt: string; updatedAt: string };
type State = { version: 2; clients: Client[]; audit: AuditEntry[] };
type LegacyState = { installation?: Omit<Client, "id" | "slug" | "createdAt">; audit?: Array<Omit<AuditEntry, "clientId">> };

const dataPath = process.env.DATA_PATH ?? path.join(process.cwd(), "data", "state.json");
if (process.env.NODE_ENV === "production" && (!process.env.CONFIG_ENCRYPTION_KEY || process.env.CONFIG_ENCRYPTION_KEY.length < 32 || ["generate-another-long-random-value", "orbit-local-development"].includes(process.env.CONFIG_ENCRYPTION_KEY))) throw new Error("Producción requiere CONFIG_ENCRYPTION_KEY de 32+ caracteres");
const secret = crypto.createHash("sha256").update(process.env.CONFIG_ENCRYPTION_KEY ?? process.env.SESSION_SECRET ?? "orbit-local-development").digest();
const blank = (): State => ({ version: 2, clients: [], audit: [] });
const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "cliente";
const administrativeActions = new Set(["client.create", "client.configure", "connection.test", "api_key.rotate"]);
const isMcpAction = (entry: AuditEntry) => !administrativeActions.has(entry.action);

function encrypt(value: string) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", secret, iv); const body = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${body.toString("base64url")}`; }
function decrypt(value: string) { if (!value) return ""; const [iv, tag, body] = value.split(".").map((part) => Buffer.from(part, "base64url")); const decipher = crypto.createDecipheriv("aes-256-gcm", secret, iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(body), decipher.final()]).toString("utf8"); }
function write(state: State) { fs.mkdirSync(path.dirname(dataPath), { recursive: true }); const temporary = `${dataPath}.${process.pid}.${crypto.randomUUID()}.tmp`; fs.writeFileSync(temporary, JSON.stringify(state, null, 2), { mode: 0o600 }); fs.renameSync(temporary, dataPath); try { fs.chmodSync(dataPath, 0o600); } catch {} }
function locked<T>(operation: () => T): T { fs.mkdirSync(path.dirname(dataPath), { recursive: true }); const lockPath = `${dataPath}.lock`; let descriptor = -1; for (let attempt = 0; attempt < 100; attempt += 1) { try { descriptor = fs.openSync(lockPath, "wx", 0o600); fs.writeFileSync(descriptor, `${process.pid}:${Date.now()}`); break; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; try { if (Date.now() - fs.statSync(lockPath).mtimeMs > 30_000) fs.unlinkSync(lockPath); } catch {} Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 25); } } if (descriptor < 0) throw Object.assign(new Error("El almacenamiento está ocupado; intenta nuevamente"), { status: 503 }); try { return operation(); } finally { try { fs.closeSync(descriptor); } catch {} try { fs.unlinkSync(lockPath); } catch {} } }
function migrate(raw: LegacyState): State {
  if (!raw.installation) return blank();
  const id = crypto.randomUUID(); const now = new Date().toISOString();
  const client: Client = { id, slug: slugify(raw.installation.companyName || "cliente"), companyName: raw.installation.companyName || "Mi empresa", siigoUsername: raw.installation.siigoUsername || "", accessKeyEncrypted: raw.installation.accessKeyEncrypted || "", partnerId: raw.installation.partnerId || "", apiKeyHash: raw.installation.apiKeyHash || "", apiKeyPrefix: raw.installation.apiKeyPrefix || "", connectionStatus: raw.installation.connectionStatus || "unconfigured", createdAt: now, updatedAt: raw.installation.updatedAt || now };
  return { version: 2, clients: [client], audit: (raw.audit ?? []).map((entry) => ({ ...entry, clientId: id })) };
}
function read(): State { try { const raw = JSON.parse(fs.readFileSync(dataPath, "utf8")) as State | LegacyState; if ((raw as State).version === 2 && Array.isArray((raw as State).clients)) return raw as State; const migrated = migrate(raw as LegacyState); write(migrated); return migrated; } catch { return blank(); } }
function uniqueSlug(state: State, name: string, excludeId?: string) { const base = slugify(name); let slug = base; let suffix = 2; while (state.clients.some((client) => client.slug === slug && client.id !== excludeId)) slug = `${base}-${suffix++}`; return slug; }
function publicClient(item: Client, audit: AuditEntry[]) { const clientAudit = audit.filter((entry) => entry.clientId === item.id && isMcpAction(entry)); const lastAction = clientAudit[0]; return { id: item.id, slug: item.slug, companyName: item.companyName, siigoUsername: item.siigoUsername, partnerId: item.partnerId, hasAccessKey: Boolean(item.accessKeyEncrypted), apiKeyPrefix: item.apiKeyPrefix, connectionStatus: item.connectionStatus, createdAt: item.createdAt, updatedAt: item.updatedAt, totalActions: clientAudit.length, failedActions: clientAudit.filter((entry) => entry.status === "failed").length, lastActionAt: lastAction?.at ?? null } }

export const store = {
  clients() { const state = read(); return state.clients.map((item) => publicClient(item, state.audit)); },
  client(id: string) { const state = read(); const item = state.clients.find((client) => client.id === id); if (!item) throw Object.assign(new Error("Cliente no encontrado"), { status: 404 }); return publicClient(item, state.audit); },
  createClient(input: { companyName: string; siigoUsername?: string; accessKey?: string; partnerId?: string }) { const id = locked(() => { const state = read(); const now = new Date().toISOString(); const item: Client = { id: crypto.randomUUID(), slug: uniqueSlug(state, input.companyName), companyName: input.companyName.trim(), siigoUsername: input.siigoUsername?.trim() ?? "", accessKeyEncrypted: input.accessKey?.trim() ? encrypt(input.accessKey.trim()) : "", partnerId: input.partnerId?.trim() ?? "", apiKeyHash: "", apiKeyPrefix: "", connectionStatus: "unconfigured", createdAt: now, updatedAt: now }; state.clients.push(item); write(state); return item.id; }); this.audit(id, "client.create", "success", "Cliente creado"); return this.client(id); },
  credentials(id: string) { const state = read(); const item = state.clients.find((client) => client.id === id); if (!item) throw Object.assign(new Error("Cliente no encontrado"), { status: 404 }); if (!item.siigoUsername || !item.accessKeyEncrypted || !item.partnerId) throw new Error("Completa las credenciales de Siigo"); return { username: item.siigoUsername, accessKey: decrypt(item.accessKeyEncrypted), partnerId: item.partnerId }; },
  configure(id: string, input: { companyName: string; siigoUsername: string; accessKey?: string; partnerId: string }) { locked(() => { const state = read(); const item = state.clients.find((client) => client.id === id); if (!item) throw Object.assign(new Error("Cliente no encontrado"), { status: 404 }); const cleanAccessKey = input.accessKey?.trim(); item.companyName = input.companyName.trim(); item.slug = uniqueSlug(state, item.companyName, item.id); item.siigoUsername = input.siigoUsername.trim(); item.partnerId = input.partnerId.trim(); if (cleanAccessKey) item.accessKeyEncrypted = encrypt(cleanAccessKey); item.connectionStatus = "unconfigured"; item.updatedAt = new Date().toISOString(); write(state); }); return this.client(id); },
  setConnectionStatus(id: string, status: Client["connectionStatus"]) { locked(() => { const state = read(); const item = state.clients.find((client) => client.id === id); if (!item) return; item.connectionStatus = status; item.updatedAt = new Date().toISOString(); write(state); }); },
  rotateApiKey(id: string) { const apiKey = locked(() => { const state = read(); const item = state.clients.find((client) => client.id === id); if (!item) throw Object.assign(new Error("Cliente no encontrado"), { status: 404 }); const value = `orb_${crypto.randomBytes(28).toString("base64url")}`; item.apiKeyHash = crypto.createHash("sha256").update(value).digest("hex"); item.apiKeyPrefix = `${value.slice(0, 10)}…`; item.updatedAt = new Date().toISOString(); write(state); return value; }); this.audit(id, "api_key.rotate", "success", "API key rotada"); return apiKey; },
  verifyApiKey(value: string, requestedClientId?: string) { if (!value) return null; const actual = crypto.createHash("sha256").update(value).digest("hex"); const client = read().clients.find((item) => item.apiKeyHash && (!requestedClientId || item.id === requestedClientId) && item.apiKeyHash.length === actual.length && crypto.timingSafeEqual(Buffer.from(item.apiKeyHash), Buffer.from(actual))); return client?.id ?? null; },
  audit(clientId: string, action: string, status: AuditStatus, detail: string, durationMs?: number, extra: { errorCode?: string; requestId?: string } = {}) { locked(() => { const state = read(); state.audit.unshift({ id: crypto.randomUUID(), clientId, at: new Date().toISOString(), action, status, detail: detail.slice(0, 800), durationMs, ...extra }); state.audit = state.audit.slice(0, 5000); write(state); }); },
  audits(clientId?: string, limit = 100) { const entries = read().audit; return entries.filter((entry) => !clientId || entry.clientId === clientId).slice(0, limit); },
  mcpAudits(clientId: string, limit = 100) { return read().audit.filter((entry) => entry.clientId === clientId && isMcpAction(entry)).slice(0, limit); },
  errors(clientId: string) { return read().audit.filter((entry) => entry.clientId === clientId && entry.status === "failed").slice(0, 100); },
  usage(clientId: string, period: string) { const hours = period === "24h" ? 24 : period === "7d" ? 24 * 7 : period === "90d" ? 24 * 90 : 24 * 30; const bucketCount = period === "24h" ? 24 : period === "7d" ? 7 : period === "90d" ? 12 : 30; const span = hours * 3_600_000; const bucketSize = span / bucketCount; const now = Date.now(); const entries = read().audit.filter((entry) => entry.clientId === clientId && isMcpAction(entry) && new Date(entry.at).getTime() >= now - span); const buckets = Array.from({ length: bucketCount }, (_, index) => ({ at: new Date(now - span + bucketSize * (index + 1)).toISOString(), success: 0, failed: 0, total: 0 })); for (const entry of entries) { const index = Math.min(bucketCount - 1, Math.max(0, Math.floor((new Date(entry.at).getTime() - (now - span)) / bucketSize))); buckets[index].total += 1; if (entry.status === "success") buckets[index].success += 1; if (entry.status === "failed") buckets[index].failed += 1; } return { period, total: entries.length, success: entries.filter((e) => e.status === "success").length, failed: entries.filter((e) => e.status === "failed").length, buckets }; }
};
